config/routes.rb
Confiture::Application.routes.draw do
  devise_for :customers
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root :to => 'home#index'

     resources :ingredients
     resources :products

end

app/models/address.rb
class Address < ActiveRecord::Base
	has_one :customer
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :products
	def add_item(product_id)
	  item = items.where('product_id = ?', product_id).first
	  if item
	    item.quantity + 1
	    save
	  else
	    cart.items << Item.new(product_id: product_id, quantity: 1)
	  end
	  save
	end
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders
  has_many :addresses
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :type
  has_many :ingredientproducts
  has_many :products, :through => :ingredientproducts
end

app/models/ingredientproduct.rb
class Ingredientproduct < ActiveRecord::Base
  belongs_to :ingredient 
  belongs_to :product
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :products
	has_one :cart
	
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :customer
  has_many :rows
  has_many :products, :through => :rows
  belongs_to :sendto, :class_name => "Address", :foreign_key => :id
  belongs_to :invoiceto, :class_name => "Address", :foreign_key => :id
  scope :by_customer, lambda{ |id| where(customer_id: id) unless id.nil? }
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :ingredientproducts
  has_many :rows
  has_many :orders, :through => :rows
  has_many :ingredients, :through => :ingredientproducts

  accepts_nested_attributes_for :ingredientproducts
end

app/models/row.rb
class Row < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
end

app/models/type.rb
class Type < ActiveRecord::Base
	has_many :ingredients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@products = Product.all
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end

  def new
  	@ingredient = Ingredient.new
  end

  def create
  	@ingredient = Ingredient.new(ingredient_params)
  	@ingredient.save
  end

  private
  
  def ingredient_params
    params.require(:ingredient).permit(:name, :priceUnit, :type_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  	product = @product.ingredientproducts.build
  end

  def create
    @product = Product.new(product_params)
    @product.save
  end

  private
  
  def product_params
    params.require(:product).permit(:name, :description, :price, :ingredientproducts_attributes => [:ingredient_id, :quantity])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/customers/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/home/index.html.erb
<div class="main_content">
	<ul class="liste_produits">
		<% @products.each do |f| %>
			<li class="item_list">
				<%= image_tag("confiture-babane.jpg", :alt => "Pot de banane") %>
				<p><%= f.name %></p>
				<p><%= f.description %></p>
				<p><%= f.price %> €</p>
			</li>
		<% end %>
	</ul>
</div>

app/views/ingredients/create.html.erb
<div class="main_content liste_produits">
	<h2>Nouvel ingrédient créé</h2>
	<ul class="item_list">
		<li>Nom : <%= @ingredient.name %></li>
		<li>Prix : <%= @ingredient.priceUnit %></li>
	</ul>
	<div class="foot_link_content">
		<%= link_to 'Ajout d\'un nouvel ingredient', new_ingredient_url() %>
		<br />
		<%= link_to 'Retour à la liste des ingredients', ingredients_path() %>
	</div>
</div>

app/views/ingredients/index.html.erb
<div class="main_content liste_produits">
		<h2>Liste des ingrédients :</h2>
		<% @ingredients.each do |i| %>
			<ul class="item_list">
				<li>Nom : <%= i.name %></li>
				<li>Prix : <%= i.priceUnit %></li>
			</ul>
		<% end %>
	<div class="foot_link_content"><%= link_to 'Nouvel ingredient', new_ingredient_url()  %></div>
</div>

app/views/ingredients/new.html.erb
<div class="main_content liste_produits">
	<%= form_for(@ingredient) do |f| %>
		<h2 class="subtitle">Création d'un ingrédient</h2>
		<%= label_tag(:name, 'Label') %>
		<%= f.text_field :name, :autofocus => true %>

		<%= label_tag(:priceUnit, "Prix") %>
		<%= f.text_field :priceUnit %>

		<%= label_tag(:type, "Type") %>
		<%= f.collection_select :type_id, Type.order(:name),:id,:name, include_blank: true  %>

		<div><%= f.submit "Nouvel ingredient", :class => 'submit_button' %></div>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Confiture</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "shared/header" %>
<%= yield %>

</body>
</html>

app/views/products/create.html.erb
<div class="main_content liste_produits">
	<h2>Nouveau produit créé</h2>
	<ul class="item_list">
		<li>Nom : <%= @product.name %></li>
		<li>Prix : <%= @product.price %></li>
		<li>Description : <%= @product.description %></li>
	</ul>
	<div class="foot_link_content">
		<%= link_to 'Ajout d\'un nouveau produit', new_product_url() %>
		<br />
		<%= link_to 'Retour à la liste des produits', products_path() %>
	</div>
</div>

app/views/products/index.html.erb
<div class="main_content liste_produits">
		<h2>Liste des produits :</h2>
		<% @products.each do |p| %>
			<ul class="item_list">
				<li>Nom : <%= p.name %></li>
				<li>Description : <%= p.description %></li>
				<li>Prix : <%= p.price %></li>
			</ul>
		<% end %>
	<div class="foot_link_content"><%= link_to 'Nouveau produit', new_product_url()  %></div>
</div>

app/views/products/new.html.erb
<div class="main_content liste_produits">
	<%= form_for(@product) do |f| %>
		<h2 class="subtitle">Création d'un produit</h2>
		<%= label_tag(:name, 'Label') %>
		<%= f.text_field :name, :autofocus => true %>

		<%= label_tag(:price, "Prix") %>
		<%= f.text_field :price %>

		<%= label_tag(:description, "Description") %>
		<%= f.text_field :description %>
		<%= f.fields_for :ingredientproducts do |builder| %>
			<%= label_tag(:ingredient_id, "Ingredients") %>
			<%= builder.collection_select :ingredient_id, Ingredient.order(:name),:id,:name, include_blank: true  %>

			<%= label_tag(:quantity, "Ingredient Quantité ?") %>
			<%= builder.text_field :quantity %>
	    <% end %>

		<div><%= f.submit "Nouveau produit", :class => 'submit_button' %></div>
	<% end %>
</div>

app/views/shared/_header.html.erb
<header class="header">
	<div class="header_content">
		<div class="button_menu">
			<%= image_tag("menu.png", :alt => "bouton menu") %>
		</div>
		<h1 class="title_header">Confi Cool Store </h1>
		<% if admin_user_signed_in? %>
			<div class="nav">
				<ul>
					<li id="first"><%= link_to 'Gestion des ingredients', ingredients_path() %></li>
					<li><%= link_to 'Gestion des produits', products_path() %></li>
					<li>Gestion des clients</li>
					<li id="last">Gestion des Marklors</li>
				</ul>
			</div>
		<% end %>
		<%= render "shared/menu" %>
	</div>
</header>

app/views/shared/_menu.html.erb
<div class="layer_account">
	<h2 class="button_account">Mon compte</h2>
	<div class="invisible_layout">
		<% if customer_signed_in? %>
			 <% user = current_customer %>
			 <%= user.email %>
			 <%= button_to "Déconnexion", destroy_session_path(:customer), :method => :delete, :class => 'submit_button' %>
		<% else %>
		<div class="content_account">
			<%= form_for(Customer.new, :as => :customer, :url => session_path(:customer)) do |f| %>
				<h2 class="subtitle">Se connecter</h2>
				<%= label_tag(:mail, "EMAIL") %>
				<%= f.email_field :email, :autofocus => true %>

				<%= label_tag(:password, "MOT DE PASSE") %>
				<%= f.password_field :password %>

				<div><%= f.submit "Valider", :class => 'submit_button' %></div>
			<% end %>
			<h2 class="subtitle subscribe_button">Inscription</h2>
		</div>

			<div class='content_subscribe'>
			<%= form_for(Customer.new, :as => :customer, :url => registration_path(:customer)) do |f| %>
				<h2 class="subtitle">S'inscrire</h2>
				<%= label_tag(:email, 'EMAIL') %>
				<%= f.email_field :email, :autofocus => true %>

				<%= label_tag(:pasword, "MOT DE PASSE") %>
				<%= f.password_field :password %>

				<%= label_tag(:password, "CONFIRMER MOT DE PASSE") %>
				<%= f.password_field :password_confirmation %>

				<div><%= f.submit "Valider", :class => 'submit_button' %></div>
			<% end %>
			<h2 class="subtitle account_button">Connexion / Retour</h2>
		</div>
	<% end %>
	</div>
</div>